// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loxpxbwdnyklwtjnogfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxveHB4YndkbnlrbHd0am5vZ2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTU5MTUsImV4cCI6MjA2Mzg5MTkxNX0.tFH3zRXKfOkvyzvbv9nW2iKDUmOHAfaB9917RubL7WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);